# Generated by Django 5.2.1 on 2025-05-18 16:37

import api.model.Person
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[api.model.Person.validate_safe_name], verbose_name='username'),
        ),
    ]
