# Generated by Django 5.2.1 on 2025-05-18 20:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_person_name_alter_person_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Tag ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Name must contain only letters and numbers, no spaces or special characters.', regex='^[a-zA-Z0-9]+$')], verbose_name='Tag Name')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Task ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Cannot contain HTML tags.', regex='^[^<>]*$')], verbose_name='Task Name')),
                ('description', models.TextField(validators=[django.core.validators.RegexValidator(message='Cannot contain HTML tags.', regex='^[^<>]*$')], verbose_name='Task Description')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('PASSED', 'PASSED')], default='PENDING', max_length=20, verbose_name='Task Status')),
                ('priority', models.CharField(choices=[('LOW', 'LOW'), ('MED', 'MED'), ('HIGH', 'HIGH')], default='LOW', max_length=20, verbose_name='Task Priority')),
                ('deadline', models.DateTimeField(verbose_name='Task Deadline')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Task Create')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Task Update')),
                ('personid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_tasks', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='task_tags', to='api.tag')),
            ],
        ),
    ]
