# Generated by Django 5.2.1 on 2025-05-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tag_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='personnal_img',
            field=models.ImageField(blank=True, default='images/default_personal.png', upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='wallpaper_img',
            field=models.ImageField(blank=True, default='images/default_wallpaper.png', upload_to='wallpapers/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='task_tags', to='api.tag', verbose_name='Task Tags'),
        ),
    ]
