# Generated by Django 5.2.1 on 2025-06-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ingredient_product_alter_user_phone_numbers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='stock_unit_count',
            field=models.IntegerField(default=0, verbose_name='stock units'),
        ),
    ]
